version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: marayat/server:v1.0.6
    restart: always
    environment:
      - PORT=8000
      - MONGO_URI=mongodb+srv://marayat:marayat@cluster0.hbazy.mongodb.net/starter-project-react?retryWrites=true&w=majority
    networks:
      - my_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: marayat/client:v1.0.7
    environment:
      - API_URL=http://server:8000
    restart: always
    networks:
      - my_network

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./certbot/webroot:/var/www/certbot
      # - ./certbot/conf:/etc/letsencrypt
    ports:
      - "3000:80"
    # ports:
    #   - "80:80"
    #   - "443:443"
    depends_on:
      - server
      - client
    restart: always
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/webroot:/var/www/certbot
  #     - ./certbot/conf:/etc/letsencrypt
  #   command:  certonly --standalone --email marayat.dev@gmail.com --agree-tos --no-eff-email -d marayatdev.online
  #   networks:
  #     - my_network

networks:
  my_network:
    driver: bridge
